// Firebase Configuration - Generated by EcoDocs Setup
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js';
import { getDatabase, ref, set, get, onValue, update, remove } from 'https://www.gstatic.com/firebasejs/10.7.1/firebase-database.js';

const firebaseConfig = {
  apiKey: "AIzaSyBPr4X2_8JYCgXzMlTcVB0EJLhup9CdyYw",
  authDomain: "login-page-echo-file.firebaseapp.com",
  databaseURL: "https://console.firebase.google.com/u/0/project/login-page-echo-file/database/login-page-echo-file-default-rtdb/data/~2F",
  projectId: "login-page-echo-file",
  storageBucket: "login-page-echo-file.firebasestorage.app",
  messagingSenderId: "200723524735",
  appId: "1:200723524735:web:9eaed6ef10cbc2c406234a"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const database = getDatabase(app);

// Export for global use
window.firebaseApp = app;
window.firebaseDB = database;
window.firebaseRef = ref;
window.firebaseSet = set;
window.firebaseGet = get;
window.firebaseOnValue = onValue;
window.firebaseUpdate = update;
window.firebaseRemove = remove;

console.log("✅ Firebase initialized successfully!");

// Helper functions for EcoDocs
window.FirebaseHelper = {
  // Save all users data
  async saveAllUsers(allUsersData) {
    try {
      await set(ref(database, 'users'), allUsersData);
      return true;
    } catch (error) {
      console.error('Error saving users:', error);
      return false;
    }
  },

  // Load all users data
  async loadAllUsers() {
    try {
      const snapshot = await get(ref(database, 'users'));
      if (snapshot.exists()) {
        return snapshot.val();
      }
      return {};
    } catch (error) {
      console.error('Error loading users:', error);
      return {};
    }
  },

  // Listen to real-time changes
  listenToUsers(callback) {
    const usersRef = ref(database, 'users');
    onValue(usersRef, (snapshot) => {
      const data = snapshot.exists() ? snapshot.val() : {};
      callback(data);
    });
  },

  // Save user docs
  async saveUserDocs(username, docs) {
    try {
      await set(ref(database, `users/${username}/docs`), docs);
      return true;
    } catch (error) {
      console.error('Error saving docs:', error);
      return false;
    }
  }
};
